# サイトの基本URLを設定します
baseURL = "https://hiroki-takase.github.io/Handbook-Sample/"

# サイトの言語コードを設定します
languageCode = "ja-jp"

# サイトのタイトルを設定します
title = "Sample Handbook"

# 使用するテーマを設定します
theme = "book"

# 相対URLを有効にします
relativeUrls=false

# 
canonifyURLs=true

# URLの小文字化を無効にします
disablePathToLower = false

# Git情報を有効にします
enableGitInfo = false

[markup]
  [markup.goldmark.renderer]
  # 安全でないHTMLを許可します
  unsafe = true
  [markup.tableOfContents]
  # 目次の開始レベルを設定します
  startLevel = 1

[menu]
#  [[menu.before]]
#  name = "GitLab"
#  url = ""
#  weight = 1
[[menu.after]]
# メニューに表示する名前を設定します
name = ""
# メニューのURLを設定します
url = ""
# メニューの重みを設定します（表示順序に影響）
weight = 1000

# [[menu.before]] は左側のリンクの一番上に項目を追加します

[params]
  # (オプション、デフォルトはtrue) ページの右側に目次を表示するかどうかを制御します。
  # 開始レベルと終了レベルはmarkup.tableOfContents設定で制御できます。
  # ページごとにフロントマターでこのパラメータを指定することもできます。
  BookToC = 5

  # (オプション、デフォルトはなし) 書籍のロゴのパスを設定します。ロゴが
  # /static/logo.png にある場合、パスは 'logo.png' になります。
  # BookLogo = 'logo.png'

  # (オプション、デフォルトはなし) サイドメニューとしてレンダリングするリーフバンドルを設定します。
  # 指定されていない場合、ファイル構造と重みが使用されます。
  # BookMenuBundle = '/menu'

  # (オプション、デフォルトはdocs) メニューとしてレンダリングするコンテンツのセクションを指定します。
  # すべてのセクションをメニューにレンダリングするには、値を "*" に設定することもできます。
  BookSection = '*'

  # ソースリポジトリの場所を設定します。
  # '最終更新' と 'このページを編集' リンクに使用されます。
  BookRepo = 'https://github.com/HIROKI-TAKASE/Handbook-Sample'

  # 'doc' ページタイプの 'このページを編集' リンクを有効にします。
  # デフォルトでは無効です。有効にするにはコメントを外します。 'BookRepo' パラメータが必要です。
  # パスはリポジトリの 'content' ディレクトリを指す必要があります。
  # BookEditPath = '-/edit/main/content'

  # webideリンク用に追加
  # https://gitlab.com/-/ide/project/brownfield-dev/remote/handbook/edit/main/-/content/company/_index.md
  # BookRepoHost      |
  #                                 | BookGroupProject             |
  #                                                                | BookWebIdePath      |
  # BookRepoHost = 'https://gitlab.com'
  # BookRepoGroupProject = 'brownfield-dev/remote/handbook'
  # BookWebIdePath = 'edit/main/-/content/'

  # (オプション、デフォルトは2006年1月2日) ページで使用される日付形式を設定します
  # - git情報で
  # - ブログ投稿で
  #BookDateFormat = 'Jan 2, 2006'

  # (オプション、デフォルトはtrue) flexsearchを使用した検索機能を有効にします。
  # インデックスは動的に構築されるため、ウェブサイトの速度が低下する可能性があります。
  # インデックスの設定は、言語ごとにi18nフォルダで調整できます。
  BookSearch = true

  # (オプション、デフォルトはtrue) ページにコメントテンプレートを有効にします。
  # デフォルトではpartals/docs/comments.htmlにDisqusテンプレートが含まれています。
  # https://gohugo.io/content-management/comments/#configure-disqus を参照してください。
  # ページのフロントマターで同じパラメータを上書きできます。
  BookComments = false

  # /!\ これは実験的な機能であり、いつでも削除または変更される可能性があります
  # (オプション、実験的、デフォルトはfalse) マークダウンページでポータブルリンクとリンクチェックを有効にします。
  # ポータブルリンクはテキストエディタで動作し、{{< relref >}} ショートコードなしでマークダウンを書くことを可能にします。
  # テーマは、マークダウンで参照されているページが存在しない場合に警告を表示します。
  BookPortableLinks = true

[params.search]
  lang = ["ja"]  # 言語を日本語に設定

  [params.search.flexsearch]  # ここで flexsearch を table にする
    enable = true  # FlexSearch を有効化
    tokenize = "full"  # "forward" ではなく "full" を指定

[outputs]
home = ["HTML", "RSS", "JSON"]  # JSONを出力（検索用）
