name: 提案テンプレート
description: ハンドブックについて提案を打ち上げる際に使用してください。
title: "<何をどうしますか？ e.g. XXXの対応フローを変更する>"
# labels: ["update content"]
body:
# この変更が行われる理由
  - type: textarea
    attributes:
      label: この変更が行われる理由
      description: |
        - このセクションでは「何を」ではなく、「なぜ」変更するのか、その理由を記載してください。
        - 例)「ClickUP でこの件について議論しました（ClickUP の会話のコピー）。現在のプロセスは効率的ではなく、この変更により X の記述がより明確になり、Y の前進に寄与します。」
    validations:
      required: true
# 対象のハンドブックのページ情報
  - type: textarea
    attributes:
      label: この提案に関連するハンドブックページの情報
      description: |
        - この提案に関係のあるハンドブックの情報があれば記載してください。
        - ページURLやスクリーンショットを説明とともに貼り付けてください。
    validations:
      required: false
# 具体的に何をどうするか
  - type: textarea
    attributes:
      label: この提案で具体的に変更する内容
      description: |
        - 内容をこれから検討する場合は、未入力でOKです。
    validations:
      required: false

# TODO ハンドブックがデプロイされたら[こちら]のリンクを貼る
  - type: checkboxes
    attributes:
      label: チェック項目
      description: |
        - この提案を作成する前に確認してください。
      options:
      - label: Labelsに「この提案の緊急度」を1つ設定している
        required: true
      - label: Assigneesに「この提案を担当するメンテナー」が設定されている。
        required: true