name: 新規でハンドブックの内容を作成する。
description: ハンドブックに新規の内容を記載するときはこのテンプレートを使用してください。
title: "<何をどうしますか？ e.g. XXXの対応フローを作成する>"
labels: ["new content"]
body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Thanks for taking the time to fill out this bug report!
  # - type: checkboxes
  #   id: checks
  #   attributes:
  #     options:
  #       - label: >
  #           I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).
  #         required: true
  - type: textarea
    attributes:
      label: この変更が行われる理由
      description: |
        - このセクションでは「何を」ではなく、「なぜ」変更するのか、その理由を記載してください。
          - e.g. 「ClickUP でこの件について議論しました（ClickUP の会話のコピー）。現在のプロセスは効率的ではなく、この変更により X の記述がより明確になり、Y の前進に寄与します。」
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 緊急度
      description: |
        - Labelに緊急レベルを設定してください。
        | レベル    | 定義 | 具体例 |
|----------|------|------|
| **Critical** | ・ 業務が完全に停止する、または極めて深刻な混乱を引き起こす状態。<br> ・「これが原因で全く業務が進まない」といった状況。 | ・例1：ハンドブックの重要なセットアップ手順が誤って記載されており、その結果、エンジニアが開発環境を構築できず、プロジェクト全体が開始できない。<br><br>・例2：社内承認プロセスの必須リンクや手順が欠落しており、発注や契約が全く進まない。 |
| **High** | ・業務に大きな支障や混乱を生じさせ、遅延を引き起こす状態。<br> ・業務は完全には停止していない場合。 | ・例1：内部プロセスの記載が不明瞭で、担当者間で認識のずれが発生。重要案件の処理が大幅に遅れ、業務の進行に大きな遅延をもたらしている。<br><br>・例2：ハンドブック内の一部表現が曖昧で、担当者間で解釈の違いが生じ、無駄な確認作業や再作業が発生する可能性がある。<br><br>・例3：更新情報が一部反映されておらず、古い情報を元に作業が進むため、後で修正が必要となる場合。 |
| **Low** | ・業務への影響は最小限で、主に表現の改善や見た目の品質向上を目的とした問題。 | ・例1：誤字脱字や軽微な文法ミスがあるが、内容の理解や業務遂行には支障はない。 |
      options:
      - label: 対応済み
        required: true
  # - type: input
  #   id: platform
  #   attributes:
  #     label: Platform
  #     description: >
  #       Please provide the output of ``import platform; print(platform.platform())``
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: method
  #   attributes:
  #     label: ドロップボックスで選択
  #     multiple: true
  #     description: >
  #       このフォームの説明
  #     options:
  #       - オプション1
  #       - オプション2
  #   validations:
  #     required: true
  # - type: textarea
  #   id: logs
  #   attributes:
  #     label: Installation Logs
  #     description: >
  #       If possible, please copy and paste the installation logs when attempting to install pandas.
  #     value: >
  #       <details>


  #       Replace this line with the installation logs.


  #       </details>