name: 新規でハンドブックの内容を作成する。
description: ハンドブックに新規の内容を記載するときはこのテンプレートを使用してください。
title: "<何をどうしますか？ e.g. XXXの対応フローを作成する>"
labels: ["new content"]
body:
  # - type: markdown
  #   attributes:
  #     value: |
  #       Thanks for taking the time to fill out this bug report!
  # - type: checkboxes
  #   id: checks
  #   attributes:
  #     options:
  #       - label: >
  #           I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).
  #         required: true
  - type: textarea
    attributes:
      label: この変更が行われる理由
       description: >
        このセクションでは「何を」ではなく、「なぜ」変更するのか、その理由を記載してください。
        e.g. 「ClickUP でこの件について議論しました（ClickUP の会話のコピー）。現在のプロセスは効率的ではなく、この変更により X の記述がより明確になり、Y の前進に寄与します。」
    validations:
      required: true
  # - type: input
  #   id: platform
  #   attributes:
  #     label: Platform
  #     description: >
  #       Please provide the output of ``import platform; print(platform.platform())``
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: method
  #   attributes:
  #     label: ドロップボックスで選択
  #     multiple: true
  #     description: >
  #       このフォームの説明
  #     options:
  #       - オプション1
  #       - オプション2
  #   validations:
  #     required: true
  # - type: textarea
  #   id: logs
  #   attributes:
  #     label: Installation Logs
  #     description: >
  #       If possible, please copy and paste the installation logs when attempting to install pandas.
  #     value: >
  #       <details>


  #       Replace this line with the installation logs.


  #       </details>